### ISSUE TITLE
Request for C version of the code

### ISSUE THREAD

**Issue by Yu3H0** [chengpeng-wang/LLMDFA#1]
Hello,

I've been really impressed with your work! I noticed in your paper that you mentioned testing with the Juliet Test Suite for C. I also noticed that the current prompts seem to be tied to Java, suggesting that modifications might be needed beyond just the `src/TSAgent` directory mentioned in the README. I'm very interested in seeing how you implemented this and would be incredibly grateful if you could share the C version of your code.

Thanks in advance for your time and consideration.

**Comment by chengpeng-wang** [comment]
Thank you for your interests in our work. We have been polishing and re-organizing the implementations of our recent works. We open-sourced [LLMSCAN](https://github.com/PurCL/LLMSCAN/blob/main/README.md) just now, a framework that offers necessary tools for LLM-based static analysis. Currently, it can support C/C++, Python, and Java. 

If you concentrate on C/C++ program analysis, you can refer to the file [`program_parser.py`](https://github.com/PurCL/LLMSCAN/blob/java/src/parser/program_parser.py) in the cpp branch. It contains the C/C++ version of utility classes and functions in `src/TSAgent` within LLMDFA.

Hope our tools can help you implement your prototype.

**Comment by Yu3H0** [comment]
Thank you for your update and for open-sourcing LLMSCAN!

Regarding the prompt, for example, "You are a Java programmer and very good at analyzing Java code. Particularly, you are good at understanding single Java functions."

Do you have any suggestion about a quick way to modify this prompt to adapt it for C/C++ analysis?

**Comment by chengpeng-wang** [comment]
Haha. Just rephrase it as "You are a C/C++ programmer and very good at analyzing C/C++ code. Particularly, you are good at understanding single C/C++ functions."

The more important prompts are the ones used in the dataflow summarization. If you want to migrate LLMDFA to support C/C++ analysis, you may need to show several few-shot examples that illustrate typical dataflow patterns in C/C++ programs. Of course, you can also rephrase the current Java examples directly.

**Comment by Yu3H0** [comment]
cool, thank you!
